/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "secondary-fixed": "#cee5ff",
        "surface-container-high": "#e7e8e9",
        "secondary": "#4a6178",
        "surface-container": "#edeeef",
        "secondary-container": "#cae2fe",
        "secondary-fixed-dim": "#b1c9e4",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "surface-dim": "#d9dadb",
        "primary-fixed-dim": "#a9c7ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed": "#ffdbcb",
        "inverse-on-surface": "#f0f1f2",
        "tertiary": "#793100",
        "outline": "#727783",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "surface": "#f8f9fa",
        "tertiary-fixed-dim": "#ffb691",
        "tertiary-container": "#9f4300",
        "on-secondary-fixed-variant": "#32495f",
        "on-primary-fixed-variant": "#00468c",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#4e657c",
        "inverse-primary": "#a9c7ff",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#005db6",
        "on-surface": "#191c1d",
        "on-primary-container": "#c8daff",
        "on-background": "#191c1d",
        "primary-container": "#005eb8",
        "outline-variant": "#c2c6d4",
        "primary": "#00478d",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424752",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
